name: CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Read .nvmrc
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
              id: nvm
            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v1
              with:
                  node-version: '${{ steps.nvm.outputs.NVMRC }}'
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint
            - name: Compile TypeScript
              run: yarn tsc
            - name: Test
              run: yarn test
